### ISSUE TITLE
TypeError on dB gain

### ISSUE THREAD

**Issue by AndreaDiPietro92** [fsmMLK/inkscapeBodePlot#1]
Error on bode plot (in dB gain)
```
/home/user/.config/inkscape/extensions/bodePlot/bodePlot.py:166: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  signFunc = lambda x: ('+', '-')[x < 0]
Error: yLim is invalid.Traceback (most recent call last):
  File "/home/user/.config/inkscape/extensions/bodePlot/bodePlot.py", line 608, in <module>
    plot.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/user/.config/inkscape/extensions/bodePlot/bodePlot.py", line 260, in effect
    [graph, limits, origin] = inkPlot.plot.cartesian(self, root_layer, freqData, gainData, position, xLabel=fLabel, yLabel=gLabel,
  File "/home/user/.config/inkscape/extensions/inkscapeMadeEasy/inkscapeMadeEasy_Plot.py", line 1145, in cartesian
    [axisObj, limits, origin] = axis.cartesian(ExtensionBaseObj, axisGroup, Xlimits, Ylimits, position, xLabel=xLabel, yLabel=yLabel,
TypeError: cannot unpack non-iterable int object
```

**Comment by fsmMLK** [comment]
I think you might have a problem with the limits. The error message is mentioning 'Error: yLim is invalid'. Anyway, I will upload a new version soon to fix other bugs.
